apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myproject
spec:
  hostAliases:
  - ip: "10.142.0.3"
    hostnames:
    - "repo.tortuga.prv"
  - ip: "10.142.0.2"
    hostnames:
    - "jenkins.tortuga.prv"
  replicas: 1
  template:
    metadata:
      labels:
        app: myproject
    spec:
      containers:
      - name: myproject
        image: repo.tortuga.prv/myproject:lastest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: kubeadmin