apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myfirstproject
spec:
  hostAliases:
  - ip: "10.142.0.3"
    hostnames:
    - "repo.tortuga.prv"
  - ip: "10.142.0.2"
    hostnames:
    - "jenkins.tortuga.prv"
  replicas: 1
  template:
    metadata:
      labels:
        app: myfirstproject
    spec:
      containers:
      - name: myfirstproject
        image: repo.tortuga.prv/myfirstproject:48
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: kubeadmin