apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myfirstproject
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myfirstproject
    spec:
      containers:
      - name: myfirstproject
        image: repo.tortuga.prv/myfirstproject:48
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: kubeadmin