apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myfirstproject
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myfirstproject
    spec:
      containers:
      - name: myfirstproject
        image: https://repo.tortuga.prv/myfirstproject:46
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: kubeadmin